#!/bin/bash

# This is a guide for running the test scripts

echo "=== TESTING API ENDPOINTS ==="
echo ""
echo "Before running the tests, please make these changes:"
echo ""
echo "1. Edit test-api.sh and test-admin-images.sh to:"
echo "   - Set your BASE_URL if different from http://localhost:3001"
echo "   - Replace TEST_USER_ID with an actual user ID from your database"
echo "   - Add your ADMIN_TOKEN from a successful admin login"
echo "   - Add your USER_TOKEN from a successful user login"
echo ""
echo "2. Run the tests:"
echo "   ./test-admin-images.sh  # For focused admin image access testing"
echo "   ./test-api.sh           # For comprehensive API testing"
echo ""
echo "3. Check the server logs to see debug messages"
echo ""
echo "Common issues:"
echo "- Make sure your server is running"
echo "- Verify your tokens aren't expired"
echo "- Confirm the user ID exists in your database"
echo "- Check that the user has an uploaded photo"
echo ""
echo "For quick token verification:"
echo "TOKEN=\"your-token-here\""
echo "echo \$TOKEN | cut -d. -f2 | base64 -D | python -m json.tool"
